sudo: required
services:
  - docker

before_install:
  - docker build -t eafolabi/react-docker -f Dockerfile.dev .

script:
  - docker run eafolabi/react-docker npm run test -- --coverage
deploy:
   provider: elasticbeanstalk
   region: "us-west-1"
   app: "docker-react"
   env: "docker-env"
   bucket_name: "elasticbeanstalk-us-west-1-787818799103"
   bucket_path: "docker-react"
   on:
     branch: master
   access_key_id: 
     secure: "$AWS_ACCESS_KEY_ID"
   secret_access_key:
     secure: "$AWS_SECRET_ACCESS_KEY"